version: '3.4'

services: 

  c-bc-apache:
    image: 127.0.0.1:5000/c-bc-apache
    build: 
      context: .
      # dockerfile: ./docker/book-collector-php/Dockerfile
      dockerfile: ./docker/c-bc-apache/Dockerfile
    volumes:
      - type: bind
        source: ./apps/book-collector/public
        target: /usr/src/bc/public
    ports: 
      - 8080:80
      # - 80:80
    configs:
      - source: c-bc-apache_httpd.conf-v1
        target: /usr/local/apache2/conf/httpd.conf
        uid: '0'
        gid: '0'
        mode: 0440
      - source: c-bc-apache_httpd-default.conf-v1
        target: /usr/local/apache2/conf/extra/httpd-default.conf
        uid: '0'
        gid: '0'
        mode: 0440
      - source: c-bc-apache_app-sf.conf-v1
        target: /usr/local/apache2/conf/extra/app-sf.conf
        uid: '0'
        gid: '0'
        mode: 0440

  c-bc-php:
    image: 127.0.0.1:5000/c-bc-php
    build: 
      context: .
      # dockerfile: ./docker/book-collector-php/Dockerfile
      dockerfile: ./docker/c-bc-php/Dockerfile
    volumes:
      - type: bind
        source: ./apps/book-collector
        target: /usr/src/bc
    # ports:
    #   - 9000:9000
    configs:
      - source: c-bc-php_php.ini-v1
        target: /usr/local/etc/php/php.ini
        uid: '0'
        gid: '0'
        mode: 0440
      - source: c-bc-php_docker-php-ext-xdebug.ini-v9
        target: /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        uid: '0'
        gid: '0'
        mode: 0440
    environment:
      XDEBUG_CONFIG: remote_host=192.168.0.102

configs:
  c-bc-apache_httpd.conf-v1:
    file: ./docker/c-bc-apache/httpd.conf
  c-bc-apache_httpd-default.conf-v1:
    file: ./docker/c-bc-apache/httpd-default.conf
  c-bc-apache_app-sf.conf-v1:
    file: ./docker/c-bc-apache/app-sf.conf
  c-bc-php_php.ini-v1:
    file: ./docker/c-bc-php/php.ini
  c-bc-php_docker-php-ext-xdebug.ini-v9:
    file: ./docker/c-bc-php/docker-php-ext-xdebug.ini
    
  # my_other_config:
  #   external: true

  # book-collector-node:
  # book-collector-mariadb:
 
# /docker/book-collector-php/php.ini /usr/local/etc/php/